//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAlarmData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalPointInfo
    {
        public Nullable<int> FkStationID { get; set; }
        public Nullable<int> PointNumber { get; set; }
        public string StationName { get; set; }
        public int PkDigitalID { get; set; }
        public Nullable<int> FkRtuID { get; set; }
        public Nullable<int> FkRtuDigitalInID { get; set; }
        public string PointName { get; set; }
        public string ShortName { get; set; }
        public Nullable<byte> SourceType { get; set; }
        public Nullable<byte> ShowType { get; set; }
        public Nullable<short> RawValue { get; set; }
        public Nullable<byte> ActualValue { get; set; }
        public Nullable<double> OffsetValue { get; set; }
        public Nullable<byte> NormalState { get; set; }
        public Nullable<byte> ChangeDetect { get; set; }
        public Nullable<byte> ReplaceValue { get; set; }
        public Nullable<byte> AudioInhibit { get; set; }
        public Nullable<byte> AlarmInhibit { get; set; }
        public Nullable<byte> RTNAlarmInhibit { get; set; }
        public Nullable<byte> AlarmPriority { get; set; }
        public Nullable<byte> LogInhibit { get; set; }
        public Nullable<byte> RTNLogInhibit { get; set; }
        public Nullable<byte> ControlType { get; set; }
        public Nullable<byte> ControlInhibit { get; set; }
        public Nullable<byte> ControlInhibitType { get; set; }
        public Nullable<byte> OutOfService { get; set; }
        public Nullable<byte> OperationTag { get; set; }
        public Nullable<int> FkRtuDigitalOutID { get; set; }
        public Nullable<int> FkCalcID { get; set; }
        public Nullable<int> FkEcaSwID { get; set; }
        public Nullable<int> CaptionCode { get; set; }
        public Nullable<int> FkAlarmGroupID { get; set; }
        public Nullable<int> FkEquipmentID { get; set; }
        public Nullable<int> FkBayID { get; set; }
        public Nullable<byte> Flashing { get; set; }
        public Nullable<byte> TelemeterFail { get; set; }
        public Nullable<byte> UnderControl { get; set; }
        public Nullable<byte> DataLinkFlag { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string DeviceType { get; set; }
        public string MACName { get; set; }
        public string Priority { get; set; }
    
        public virtual Devices Device { get; set; }
    }
}
