//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAlarmData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestorationAlarmDbContext : DbContext
    {
        public RestorationAlarmDbContext()
            : base("name=RestorationAlarmDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Devices> Device { get; set; }
        public virtual DbSet<DigitalPointInfo> DigitalPointInfo { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<RestorationAlarmLists> RestorationAlarmList { get; set; }
        public virtual DbSet<Stations> Station { get; set; }
    
        public virtual int BackUpDigitalPointInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BackUpDigitalPointInfo");
        }
    }
}
